spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/thinkfirst}
  
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}

logging:
  level:
    com.thinkfirst: INFO

