spring:
  datasource:
    url: DATABASE_URL:jdbc:postgresql://postgres:5432/thinkfirst
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}

logging:
  level:
    com.thinkfirst: INFO

